# Generated by Django 6.0.2 on 2026-04-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='updated_field',
            new_name='updated_at',
        ),
    ]
